logging:
  level:
    org.springframework.web.servlet: DEBUG

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

# BEGIN
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

jte:
  templates-path: src/main/jte
  persistent: true

# END